theme: minima
title: offset's blog
author: offset
description: Security Researcher
google_analytics: UA-114731872-1
timezone: Europe/Istanbul
twitter_username: none
github_username: ggulgun
facebook_username: none
instagram_username: none
linkedin_username: ggulgun
show_excerpts: false
disqus:
  shortname: https-ggulgun-github-io
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
