remote_theme: b2a3e8/jekyll-theme-console
listen_for_clients_preferred_style: true

google_analytics: 

header_pages:
        - index.md
        - contact.md

footer: '<a href="https://twitter.com/ggsec_">@ggsec_</a>'

plugins:
  - jekyll-feed
